/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JFrame;

/**
 *
 * @author HP
 */
public class MDIApplication extends javax.swing.JFrame {

    /**
     * Creates new form MDIApplication
     */
    public static MDIApplication instance;

    public MDIApplication() {
        initComponents();
        setTitle("Gestion des Activite");
        setExtendedState(MAXIMIZED_BOTH);

    }

    public static MDIApplication getInstance() {
        if (instance == null) {
            instance = new MDIApplication();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        activitemenu = new javax.swing.JMenuItem();
        etudiantMenu = new javax.swing.JMenuItem();
        participation = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        parac = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        ghraphe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Gestion ⚙");

        activitemenu.setMnemonic('o');
        activitemenu.setText("Activité 👓");
        activitemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activitemenuActionPerformed(evt);
            }
        });
        fileMenu.add(activitemenu);

        etudiantMenu.setMnemonic('s');
        etudiantMenu.setText("Étudiant 👥");
        etudiantMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etudiantMenuActionPerformed(evt);
            }
        });
        fileMenu.add(etudiantMenu);

        participation.setText("Participation ➕");
        participation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                participationActionPerformed(evt);
            }
        });
        fileMenu.add(participation);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Recherche 🔍");

        parac.setMnemonic('t');
        parac.setText("les participants par activité 📤");
        parac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paracActionPerformed(evt);
            }
        });
        editMenu.add(parac);

        jMenuItem2.setText("Recherche les activités ❓");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        editMenu.add(jMenuItem2);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Statistique 📊");

        ghraphe.setText("le nombre des participant par activite 📈");
        ghraphe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ghrapheActionPerformed(evt);
            }
        });
        helpMenu.add(ghraphe);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void activitemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activitemenuActionPerformed
        ActiviteForm profForm = ActiviteForm.getInstance();
        if (!profForm.isVisible()) {
            desktopPane.add(profForm);
            profForm.setVisible(true);
        }
        ;
    }//GEN-LAST:event_activitemenuActionPerformed

    private void paracActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paracActionPerformed
        // TODO add your handling code here:
        ParticipantByActivite ef = ParticipantByActivite.getInstance();
        if (!ef.isVisible()) {
            desktopPane.add(ef);
            ef.setVisible(true);
        }
    }//GEN-LAST:event_paracActionPerformed

    private void etudiantMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etudiantMenuActionPerformed
        // TODO add your handling code here:
        EtudiantForm ef = EtudiantForm.getInstance();
        if (!ef.isVisible()) {
            desktopPane.add(ef);
            ef.setVisible(true);
        }
    }//GEN-LAST:event_etudiantMenuActionPerformed

    private void participationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_participationActionPerformed
        // TODO add your handling code here:
        EnregistreParticpant EP = EnregistreParticpant.getInstance();
        if (!EP.isVisible()) {
            desktopPane.add(EP);
            EP.setVisible(true);
        }

    }//GEN-LAST:event_participationActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        RechercheActivitee ra = RechercheActivitee.getInstance();
        if (!ra.isVisible()) {
            desktopPane.add(ra);
            ra.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void ghrapheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ghrapheActionPerformed
        // TODO add your handling code here:
        ParticipationChart chart = new ParticipationChart();
        chart.setSize(800, 600);
        chart.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Fermer seulement le graphique
        chart.setLocationRelativeTo(null); // Centrer la fenêtre
        chart.setVisible(true);
    }//GEN-LAST:event_ghrapheActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem activitemenu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem etudiantMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem ghraphe;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem parac;
    private javax.swing.JMenuItem participation;
    // End of variables declaration//GEN-END:variables

}
